#!/usr/bin/env node
// Writes apps/web/.env.local from the running local Supabase stack (`pnpm db:start` first).
// The values are Supabase's local-development defaults; .env.local is git-ignored (NFR SEC-4).
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const raw = execFileSync("pnpm", ["exec", "supabase", "status", "-o", "json"], { cwd: root, encoding: "utf8" });
const s = JSON.parse(raw.slice(raw.indexOf("{")));
const need = ["API_URL", "PUBLISHABLE_KEY", "SECRET_KEY", "MAILPIT_URL"];
for (const k of need) if (!s[k]) throw new Error(`supabase status is missing ${k}; is the stack running?`);

const lines = [
  "# Generated by scripts/supabase-env.mjs from the local Supabase stack. Do not commit.",
  `NEXT_PUBLIC_SUPABASE_URL=${s.API_URL}`,
  `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${s.PUBLISHABLE_KEY}`,
  "# Server-only (never NEXT_PUBLIC_): used by e2e tests and server admin code.",
  `SUPABASE_SECRET_KEY=${s.SECRET_KEY}`,
  `MAILPIT_URL=${s.MAILPIT_URL}`,
  "",
];
writeFileSync(`${root}/apps/web/.env.local`, lines.join("\n"));
console.log("Wrote apps/web/.env.local for", s.API_URL);
